version: "3.2"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_EVMOS_API=${REACT_APP_EVMOS_API}
    ports:
      - target: 80
        published: 3001
    depends_on:
      - backend
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - target: 5000
        published: 5001
    environment:
      RPC: ${RPC}
      COSMOS_RPC: ${COSMOS_RPC}
      MONGO: ${MONGO}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:4
    ports:
      - target: 27017
        published: 27018
    volumes:
      - .mongo/db/:/data/db/
    restart: on-failure
