version: "3.2"

services:
  frontend:
    image: ${FRONTEND_IMAGE:-blockexplorer-frontend}
    depends_on:
      - backend
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontendservice.loadbalancer.server.port=80"
      - "traefik.http.routers.frontendkryharouter.service=frontendservice"
      - "traefik.http.routers.frontendkryharouter.rule=Host(`explorer.evmos.kryha.io`)"
      - "traefik.http.routers.frontendkryharouter.tls=true"
      - "traefik.http.routers.frontendkryharouter.tls.certresolver=kryharesolver"

  backend:
    image: ${BACKEND_IMAGE:-blockexplorer-backend}
    environment:
      ETH_RPC_URL: ${ETH_RPC_URL}
      PORT: ${PORT}
      COSMOS_RPC: ${COSMOS_RPC}
      DB_URI: ${DB_URI}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      - mongo
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backendservice.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backendkryharouter.service=backendservice"
      - "traefik.http.routers.backendkryharouter.middlewares=api-stripprefix"
      - "traefik.http.routers.backendkryharouter.tls=true"
      - "traefik.http.routers.backendkryharouter.tls.certresolver=kryharesolver"
      - "traefik.http.routers.backendkryharouter.rule=(Host(`explorer.evmos.kryha.io`) && PathPrefix(`/api`))"

  mongo:
    image: mongo:4
    volumes:
      - .mongo/db/:/data/db/
    restart: always

  traefik:
    image: traefik:chevrotin # v2
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    environment:
      GCE_PROJECT: ${DNS_GCE_PROJECT}
      GCE_SERVICE_ACCOUNT_FILE: /etc/traefik/.gcd_credentials_kryha.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .traefik/:/etc/traefik/
    restart: always
