providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

certificatesResolvers:
  kryharesolver:
    acme:
      email: "tls@kryha.io"
      storage: "/etc/traefik/certs/kryha.json"
      dnsChallenge:
        provider: "gcloud"
